# Generated by Django 4.0.2 on 2022-03-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='homeworks/files/%Y/%m/%d', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Вложенный файл',
                'verbose_name_plural': 'Вложенные файлы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('age', models.IntegerField(verbose_name='Возраст студента')),
                ('gpa', models.FloatField(verbose_name='Средний бал')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Стундеты',
                'ordering': ('user', 'age', 'group', 'gpa'),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('full_name', models.CharField(max_length=20, verbose_name='Полное имя')),
                ('topic', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'TypeScrips'), ('ruby', 'Ruby'), ('golang', 'Golanfg'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('delphi', 'Delphi'), ('perl', 'Perl')], default='java', max_length=20, verbose_name='Предмет')),
                ('students', models.ManyToManyField(to='firstapp.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
                'ordering': ('full_name', 'topic'),
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('logo', models.ImageField(upload_to='homeworks/logos/%Y/%m/%d', verbose_name='Лого')),
                ('is_checked', models.BooleanField(default=False)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ('datatime_created',),
            },
        ),
    ]
