# Generated by Django 3.0 on 2022-03-09 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(default=2010, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datatime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('is_checked', models.BooleanField(default=False)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='homeworks',
            field=models.ManyToManyField(to='firstapp.Homework'),
        ),
    ]
