# Generated by Django 3.0 on 2022-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_group_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='Полное имя')),
                ('topic', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'TypeScrips'), ('ruby', 'Ruby'), ('golang', 'Golanfg'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('delphi', 'Delphi'), ('perl', 'Perl')], default='java', max_length=20, verbose_name='Предмет')),
                ('students', models.ManyToManyField(to='firstapp.Student')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
                'ordering': ('full_name', 'topic'),
            },
        ),
    ]
