# Generated by Django 3.0 on 2022-03-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220309_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Вложенный файл', 'verbose_name_plural': 'Вложенные файлы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('datatime_created',), 'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='homeworks',
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(default=2010, on_delete=django.db.models.deletion.PROTECT, to='firstapp.Student'),
            preserve_default=False,
        ),
    ]
