# Generated by Django 4.0.2 on 2022-04-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_homework_is_checked_file_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='firstapp.homework'),
        ),
    ]
