# Generated by Django 3.0 on 2022-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20220309_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='on_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
