# Generated by Django 3.0 on 2022-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datatime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='datatime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='account',
            name='datatime_updated',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время обновления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='datatime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='datatime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='group',
            name='datatime_updated',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время обновления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='datatime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='datatime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='professor',
            name='datatime_updated',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время обновления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='datatime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='datatime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаления'),
        ),
        migrations.AddField(
            model_name='student',
            name='datatime_updated',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время обновления'),
            preserve_default=False,
        ),
    ]
