# Generated by Django 4.0.2 on 2022-04-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_file_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='obj',
        ),
        migrations.AlterField(
            model_name='file',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='firstapp.homework', verbose_name='Домашняя работа'),
        ),
    ]
