# Generated by Django 3.0 on 2022-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_homework_on_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='on_deleted',
        ),
        migrations.AddField(
            model_name='homework',
            name='logo',
            field=models.ImageField(default=2008, upload_to='homeworks/logos/%Y/%m/%d', verbose_name='Лого'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='homeworks/files/%Y/%m/%d', verbose_name='Файл'),
        ),
    ]
